name: RSpec Tests

on:
  push:
    branches:
      - master # Change this to the branch you want to trigger the workflow on
  pull_request:
    branches:
      - master # Change this to the branch you want to trigger the workflow on

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.0 # Change this to your desired Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run RSpec tests
        run: bundle exec rspec
